[package]
name = "example_usage"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# token_limiter = { git = "https://github.com/TristanStreich/token_limiter" }
token_limiter = { path = ".." }